interface AudioFile {
  id: number;
  word: string;
  link: string;
}

export const audioFiles: AudioFile[] = [
  { id: 1, word: "Aaronites", link: "/audio/Aaronites.mp3" },
  { id: 2, word: "Ahiramites", link: "/audio/Ahiramites.mp3" },
  { id: 3, word: "Ammonites", link: "/audio/Ammonites.mp3" },
  { id: 4, word: "Amramites", link: "/audio/Amramites.mp3" },
  { id: 5, word: "Apharasathchites", link: "/audio/Apharasathchites.mp3" },
  { id: 6, word: "Archevites", link: "/audio/Archevites.mp3" },
  { id: 7, word: "Arelites", link: "/audio/Arelites.mp3" },
  { id: 8, word: "Ashbelites", link: "/audio/Ashbelites.mp3" },
  { id: 9, word: "Ashdothites", link: "/audio/Ashdothites.mp3" },
  { id: 10, word: "Ashurites", link: "/audio/Ashurites.mp3" },
  { id: 11, word: "Avites", link: "/audio/Avites.mp3" },
  { id: 12, word: "Beerothites", link: "/audio/Beerothites.mp3" },
  { id: 13, word: "Benjamites", link: "/audio/Benjamites.mp3" },
  { id: 14, word: "Berites", link: "/audio/Berites.mp3" },
  { id: 15, word: "Carmites", link: "/audio/Carmites.mp3" },
  { id: 16, word: "Danites", link: "/audio/Danites.mp3" },
  { id: 17, word: "Dinaites", link: "/audio/Dinaites.mp3" },
  { id: 18, word: "Ekronites", link: "/audio/Ekronites.mp3" },
  { id: 19, word: "Elonites", link: "/audio/Elonites.mp3" },
  { id: 20, word: "Ephrathites", link: "/audio/Ephrathites.mp3" },
  { id: 21, word: "Erites", link: "/audio/Erites.mp3" },
  { id: 22, word: "Eshtaulities", link: "/audio/Eshtaulities.mp3" },
  { id: 23, word: "Gazathites", link: "/audio/Gazathites.mp3" },
  { id: 24, word: "Gershonites", link: "/audio/Gershonites.mp3" },
  { id: 25, word: "Gezrities", link: "/audio/Gezrities.mp3" },
  { id: 26, word: "Giblites", link: "/audio/Giblites.mp3" },
  { id: 27, word: "Girgeshites", link: "/audio/Girgeshites.mp3" },
  { id: 28, word: "Gunites", link: "/audio/Gunites.mp3" },
  { id: 29, word: "Haggites", link: "/audio/Haggites.mp3" },
  { id: 30, word: "Hahochites", link: "/audio/Hahochites.mp3" },
  { id: 31, word: "Genesis", link: "/audio/Genesis.mp3" },
  { id: 32, word: "Exodus", link: "/audio/Exodus.mp3" },
  { id: 33, word: "Leviticus", link: "/audio/Leviticus.mp3" },
  { id: 34, word: "Numbers", link: "/audio/Numbers.mp3" },
  { id: 35, word: "Deuteronomy", link: "/audio/Deuteronomy.mp3" },
  { id: 36, word: "Joshua", link: "/audio/Joshua.mp3" },
  { id: 37, word: "Judges", link: "/audio/Judges.mp3" },
  { id: 38, word: "Ruth", link: "/audio/Ruth.mp3" },
  { id: 39, word: "Obadiah", link: "/audio/Obadiah.mp3" },
  { id: 40, word: "Ruth", link: "/audio/Ruth.mp3" },

  { id: 41, word: "Melchizedek", link: "/audio/Melchizedek.mp3" },
  { id: 42, word: "Menahem", link: "/audio/Menahem.mp3" },
  { id: 43, word: "Esther", link: "/audio/Esther.mp3" },
  { id: 44, word: "Jabbok", link: "/audio/Jabbok.mp3" },
  { id: 45, word: "Jordan", link: "/audio/Jordan.mp3" },
  { id: 46, word: "Alexandria", link: "/audio/Alexandria.mp3" },
  { id: 47, word: "Antioch", link: "/audio/Antioch.mp3" },
  { id: 48, word: "Babylon", link: "/audio/Babylon.mp3" },
  { id: 49, word: "Bethlehem", link: "/audio/Bethlehem.mp3" },
  { id: 50, word: "Bethshan", link: "/audio/Bethshan.mp3" },
  { id: 51, word: "Jerusha", link: "/audio/Jerusha.mp3" }, 
  { id: 52, word: "Revelation", link: "/audio/Revelation.mp3" },
  { id: 53, word: "Acharonites", link: "/audio/Acharonites.mp3" },
  { id: 54, word: "Ashdodites", link: "/audio/Ashdodites.mp3" },
  { id: 55, word: "Augustus", link: "/audio/Augustus.mp3" },
  { id: 56, word: "Azubah", link: "/audio/Azubah.mp3" },
  { id: 57, word: "Baalgad", link: "/audio/Baalgad.mp3" },
  { id: 58, word: "Gibeon", link: "/audio/Gibeon.mp3" },
  { id: 59, word: "Haggites", link: "/audio/Haggites.mp3" },
  { id: 60, word: "Hashemites", link: "/audio/Hashemites.mp3" },
  { id: 61, word: "Jehudites", link: "/audio/Jehudites.mp3" },
  { id: 62, word: "Kazathites", link: "/audio/Kazathites.mp3" },
  { id: 63, word: "Lebanites", link: "/audio/Lebanites.mp3" },
  { id: 64, word: "Mahites", link: "/audio/Mahites.mp3" },
  { id: 65, word: "Meshites", link: "/audio/Meshites.mp3" },
  { id: 66, word: "Mezrites", link: "/audio/Mezrites.mp3" },
  { id: 67, word: "Mushites", link: "/audio/Mushites.mp3" },
  { id: 68, word: "Ozites", link: "/audio/Ozites.mp3" },
  { id: 69, word: "Paltites", link: "/audio/Paltites.mp3" },
  { id: 70, word: "Peletites", link: "/audio/Peletites.mp3" },
  { id: 71, word: "Sheba", link: "/audio/Sheba.mp3" },
  { id: 72, word: "Tepalah", link: "/audio/Tepalah.mp3" },
  { id: 73, word: "Zarahites", link: "/audio/Zarahites.mp3" },
  { id: 74, word: "Abana", link: "/audio/Abana.mp3" },
  { id: 75, word: "Abiahil", link: "/audio/Abiahil.mp3" },
  { id: 76, word: "Ahava", link: "/audio/Ahava.mp3" },
  { id: 77, word: "Ahikam", link: "/audio/Ahikam.mp3" },
  { id: 78, word: "Anah", link: "/audio/Anah.mp3" },
  { id: 79, word: "Aniam", link: "/audio/Aniam.mp3" },
  { id: 80, word: "Aphik", link: "/audio/Aphik.mp3" },
  { id: 81, word: "Cestrus", link: "/audio/Cestrus.mp3" },
  { id: 82, word: "Chebar", link: "/audio/Chebar.mp3" },
  { id: 83, word: "Eli", link: "/audio/Eli.mp3" },
   { id: 84, word: "Arinon", link: "/audio/Arinon.mp3" },
{ id: 85, word: "Barnabas", link: "/audio/Barnabas.mp3" },
{ id: 86, word: "Chinnereth", link: "/audio/Chinnereth.mp3" },
{ id: 87, word: "Bethuel", link: "/audio/Bethuel.mp3" },
{ id: 88, word: "Bethshan", link: "/audio/Bethshan.mp3" },
{ id: 89, word: "Balah", link: "/audio/Balah.mp3" },
{ id: 90, word: "Asshur", link: "/audio/Asshur.mp3" },
{ id: 91, word: "Baalgad", link: "/audio/Baalgad.mp3" },
{ id: 92, word: "Aroer", link: "/audio/Aroer.mp3" },
{ id: 93, word: "Anim", link: "/audio/Anim.mp3" },
{ id: 94, word: "Anathoth", link: "/audio/Anathoth.mp3" },
{ id: 95, word: "Aijalon", link: "/audio/Aijalon.mp3" },
{ id: 96, word: "Tepalah", link: "/audio/Tepalah.mp3" },
{ id: 97, word: "Orontes", link: "/audio/Orontes.mp3" },
{ id: 98, word: "Kanah", link: "/audio/Kanah.mp3" },
{ id: 99, word: "Hasbani", link: "/audio/Hasbani.mp3" },

{ id: 100, word: "Gozan", link: "/audio/Gozan.mp3" },
{ id: 101, word: "Zibath", link: "/audio/Zibath.mp3" },
];


